/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quan.datn.view.panel;

import com.quan.datn.model.NhanVien;
import com.quan.datn.utils.DBManager;

public class MainView extends javax.swing.JPanel {

    /**
     * Creates new form MainView
     */
    private PNHome pnHome;
    private PNLeTan pnLeTan;
    private PNKhamBenh pnKhamBenh;
    private PNQLNS pnQLNS;
    private PNQLBN pnQLBN;
    private PNBaoCao pnBaoCao;
    private PNQLPB pnQLPB;
    private PNPersonInfo pNPersonInfo;
    private int select = 0;

    public MainView() {
        initComponents();
        initMenuTab();
    }

    public void initMenuTab() {
        jTabbedPane1.removeAll();
        pnHome = new PNHome();
        pnLeTan = new PNLeTan();
        pnKhamBenh = new PNKhamBenh();
        pnQLNS = new PNQLNS();
        pnQLBN = new PNQLBN();
        pnBaoCao = new PNBaoCao();
        pnQLPB = new PNQLPB();
        pNPersonInfo = new PNPersonInfo();
        pNPersonInfo.updateInfo();
        jTabbedPane1.addTab("Trang Chính", pnHome);
        
        //Bác sĩ, Y Tá, Nhân Viên
        NhanVien nhanVien = DBManager.sharedInstance.getSessionLogin();
        
        if (nhanVien.getViTri().equals("Nhân Viên")) {
            jTabbedPane1.addTab("Lễ Tân", pnLeTan);
            jTabbedPane1.addTab("Thống kê - Báo cáo", pnBaoCao);
        } else if (nhanVien.getViTri().equals("Y Tá")) {
            jTabbedPane1.addTab("Lễ Tân", pnLeTan);
            jTabbedPane1.addTab("Khám Bệnh", pnKhamBenh);
            jTabbedPane1.addTab("Quản lý bệnh nhân", pnQLBN);
            jTabbedPane1.addTab("Thống kê - Báo cáo", pnBaoCao);
        } else if (nhanVien.getViTri().equals("Bác sĩ")) {
            jTabbedPane1.addTab("Khám Bệnh", pnKhamBenh);
            jTabbedPane1.addTab("Quản lý bệnh nhân", pnQLBN);
        } else {
            jTabbedPane1.addTab("Lễ Tân", pnLeTan);
            jTabbedPane1.addTab("Khám Bệnh", pnKhamBenh);
            jTabbedPane1.addTab("Quản lý nhân sự", pnQLNS);
            jTabbedPane1.addTab("Quản lý bệnh nhân", pnQLBN);
            jTabbedPane1.addTab("Quản lý các phòng", pnQLPB);
            jTabbedPane1.addTab("Thống kê - Báo cáo", pnBaoCao);
        }
        jTabbedPane1.addTab("Thông tin cá nhân", pNPersonInfo);
        jTabbedPane1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTabbedPane1.setInheritsPopupMenu(true);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseReleased

        if (jTabbedPane1.getSelectedComponent() == pnHome) {
            System.out.println("Home");
            select = 0;
        } else if (jTabbedPane1.getSelectedComponent() == pnLeTan) {
            if (select != 1) {
                System.out.println("pnLeTan");
                select = 1;
                pnLeTan.loadData();
            }
        } else if (jTabbedPane1.getSelectedComponent() == pnKhamBenh) {
            if (select != 2) {
                System.out.println("pnKhamBenh");
                select = 2;
                pnKhamBenh.loadData();
            }
        } else if (jTabbedPane1.getSelectedComponent() == pnQLNS) {
            if (select != 3) {
                System.out.println("pnQLNS");
                select = 3;
                pnQLNS.reloadData();
            }
        } else if (jTabbedPane1.getSelectedComponent() == pnQLBN) {
            if (select != 4) {
                System.out.println("pnQLBN");
                select = 4;
                pnQLBN.reloadData();
            }

        } else if (jTabbedPane1.getSelectedComponent() == pnQLPB) {
            if (select != 5) {
                System.out.println("pnQLPB");
                select = 5;
                pnQLPB.loadData();
            }

        } else if (jTabbedPane1.getSelectedComponent() == pnBaoCao) {
            if (select != 6) {
                System.out.println("pnBaoCao");
                select = 6;
                pnBaoCao.loadData();
            }
        }

    }//GEN-LAST:event_jTabbedPane1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
