/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quan.datn.view.panel;

import com.quan.datn.model.request.BenhAnRequest;
import com.quan.datn.model.response.BenhAnResponse;
import com.quan.datn.model.response.BenhNhanResponse;
import com.quan.datn.network.APIManager;
import com.quan.datn.network.BenhAnRepository;
import com.quan.datn.network.BenhNhanRepository;
import com.quan.datn.view.CapThuoc;
import com.quan.datn.view.NhapVien;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PNKhamBenh extends javax.swing.JPanel {

    /**
     * Creates new form KhamBenh
     */
    private final BenhNhanRepository bnRepository;
    private final BenhAnRepository benhAnRepository;
    private List<BenhNhanResponse> dsBenhNhan;

    public PNKhamBenh() {
        initComponents();
        bnRepository = new BenhNhanRepository();
        benhAnRepository = new BenhAnRepository();
    }

    public void loadData() {
        new Thread(() -> {
            showListBenhNhanCho();
        }).start();
    }

    private void showListBenhNhanCho() {
        dsBenhNhan = bnRepository.getAllBenhNhanCho();
        if (!dsBenhNhan.isEmpty()) {
            DefaultTableModel mode = (DefaultTableModel) tableBenhNhan.getModel();
            mode.setRowCount(0);
            Object[] row = new Object[7];
            for (int i = 0; i < dsBenhNhan.size(); i++) {
                row[0] = i;
                row[1] = dsBenhNhan.get(i).getMaBN();
                row[2] = dsBenhNhan.get(i).getHoBn();
                row[3] = dsBenhNhan.get(i).getTenBn();
                row[4] = dsBenhNhan.get(i).getGioiTinh();
                row[5] = dsBenhNhan.get(i).getNgaySinh();
                if (dsBenhNhan.get(i).getBenhAnResponse() != null) {
                    row[6] = dsBenhNhan.get(i).getBenhAnResponse().getLyDoKham();
                } else {
                    row[6] = "";
                }
                mode.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaBN = new javax.swing.JTextField();
        txtHoBN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGioiTinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaBA = new javax.swing.JTextField();
        dsgrd = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenBN = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtYCKham = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBenhNhan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCanNang = new javax.swing.JTextField();
        txtMach = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtHuyetAp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbNhomMau = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txtNhipTho = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNhietDo = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLyDoKham = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtTinhTrangHT = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtBenhSu = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtChanDoanSoBo = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtYCThem = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtChanDoanSauCung = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtHuongDieuTri = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        txtChiPhi = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnCapThuoc = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin bệnh nhân", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(434, 300));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mã BN : ");
        jLabel5.setPreferredSize(new java.awt.Dimension(63, 26));

        txtMaBN.setEditable(false);
        txtMaBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaBN.setPreferredSize(new java.awt.Dimension(59, 25));

        txtHoBN.setEditable(false);
        txtHoBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHoBN.setPreferredSize(new java.awt.Dimension(59, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Họ : ");
        jLabel6.setPreferredSize(new java.awt.Dimension(63, 26));

        txtGioiTinh.setEditable(false);
        txtGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGioiTinh.setPreferredSize(new java.awt.Dimension(59, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Giới tính: ");
        jLabel7.setPreferredSize(new java.awt.Dimension(63, 26));

        txtMaBA.setEditable(false);
        txtMaBA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaBA.setPreferredSize(new java.awt.Dimension(59, 25));

        dsgrd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dsgrd.setText("Mã BA : ");
        dsgrd.setPreferredSize(new java.awt.Dimension(63, 26));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tên : ");
        jLabel9.setPreferredSize(new java.awt.Dimension(63, 26));

        txtTenBN.setEditable(false);
        txtTenBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenBN.setPreferredSize(new java.awt.Dimension(59, 25));

        txtNgaySinh.setEditable(false);
        txtNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNgaySinh.setPreferredSize(new java.awt.Dimension(59, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Ngày Sinh : ");
        jLabel10.setPreferredSize(new java.awt.Dimension(63, 26));

        txtDiaChi.setEditable(false);
        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiaChi.setPreferredSize(new java.awt.Dimension(59, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Địa Chỉ : ");
        jLabel11.setPreferredSize(new java.awt.Dimension(63, 26));

        txtSDT.setEditable(false);
        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSDT.setPreferredSize(new java.awt.Dimension(59, 25));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("SĐT : ");
        jLabel12.setPreferredSize(new java.awt.Dimension(63, 26));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Yêu cầu khám : ");
        jLabel13.setPreferredSize(new java.awt.Dimension(63, 26));

        txtYCKham.setEditable(false);
        txtYCKham.setColumns(20);
        txtYCKham.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtYCKham.setLineWrap(true);
        txtYCKham.setRows(5);
        jScrollPane1.setViewportView(txtYCKham);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txtHoBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMaBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dsgrd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaBA, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtTenBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dsgrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaBA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHoBN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách bệnh nhân chờ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/remove_user_30x30.png"))); // NOI18N
        jButton1.setText("<html>&emsp;&ensp;Xóa<br> Bệnh Nhân</html>");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableBenhNhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableBenhNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Bệnh Nhân", "Họ", "Tên", "Giới Tính", "Ngày Sinh", "Yêu Cầu Khám"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBenhNhan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableBenhNhan.setGridColor(new java.awt.Color(204, 255, 204));
        tableBenhNhan.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        tableBenhNhan.setMinimumSize(new java.awt.Dimension(600, 156));
        tableBenhNhan.setRowHeight(26);
        tableBenhNhan.setSelectionBackground(new java.awt.Color(183, 219, 255));
        tableBenhNhan.setSelectionForeground(new java.awt.Color(0, 102, 255));
        tableBenhNhan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBenhNhanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableBenhNhan);
        if (tableBenhNhan.getColumnModel().getColumnCount() > 0) {
            tableBenhNhan.getColumnModel().getColumn(0).setMinWidth(60);
            tableBenhNhan.getColumnModel().getColumn(0).setMaxWidth(100);
            tableBenhNhan.getColumnModel().getColumn(1).setMinWidth(130);
            tableBenhNhan.getColumnModel().getColumn(2).setMinWidth(98);
            tableBenhNhan.getColumnModel().getColumn(3).setMinWidth(130);
            tableBenhNhan.getColumnModel().getColumn(4).setMinWidth(100);
            tableBenhNhan.getColumnModel().getColumn(5).setMinWidth(150);
            tableBenhNhan.getColumnModel().getColumn(6).setMinWidth(350);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(153, 255, 153));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(204, 240, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khám", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(459, 282));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Cân nặng : ");
        jLabel14.setPreferredSize(new java.awt.Dimension(63, 26));

        txtCanNang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCanNang.setPreferredSize(new java.awt.Dimension(59, 25));
        txtCanNang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCanNangKeyPressed(evt);
            }
        });

        txtMach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMach.setPreferredSize(new java.awt.Dimension(59, 25));
        txtMach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMachKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Mạch : ");
        jLabel15.setPreferredSize(new java.awt.Dimension(63, 26));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("/phút");
        jLabel16.setPreferredSize(new java.awt.Dimension(63, 26));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Huyết Áp : ");
        jLabel17.setPreferredSize(new java.awt.Dimension(63, 26));

        txtHuyetAp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHuyetAp.setPreferredSize(new java.awt.Dimension(59, 25));
        txtHuyetAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHuyetApKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("mmHg");
        jLabel18.setPreferredSize(new java.awt.Dimension(63, 26));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Nhóm máu: ");
        jLabel19.setPreferredSize(new java.awt.Dimension(63, 26));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("kg");
        jLabel20.setPreferredSize(new java.awt.Dimension(63, 26));

        cbNhomMau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbNhomMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "O" }));
        cbNhomMau.setPreferredSize(new java.awt.Dimension(80, 25));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Nhịp thở : ");
        jLabel21.setPreferredSize(new java.awt.Dimension(63, 26));

        txtNhipTho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNhipTho.setPreferredSize(new java.awt.Dimension(59, 25));
        txtNhipTho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNhipThoKeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("lần/phút");
        jLabel22.setPreferredSize(new java.awt.Dimension(63, 26));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Nhiệt độ : ");
        jLabel23.setPreferredSize(new java.awt.Dimension(63, 26));

        txtNhietDo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNhietDo.setPreferredSize(new java.awt.Dimension(59, 25));
        txtNhietDo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNhietDoKeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("độ C");
        jLabel24.setPreferredSize(new java.awt.Dimension(63, 26));

        jPanel11.setBackground(new java.awt.Color(204, 240, 255));

        jLabel25.setBackground(new java.awt.Color(204, 204, 204));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("<html>Lý do khám </html>");
        jLabel25.setPreferredSize(new java.awt.Dimension(63, 26));

        txtLyDoKham.setEditable(false);
        txtLyDoKham.setColumns(20);
        txtLyDoKham.setRows(5);
        jScrollPane2.setViewportView(txtLyDoKham);

        txtTinhTrangHT.setColumns(20);
        txtTinhTrangHT.setRows(5);
        jScrollPane4.setViewportView(txtTinhTrangHT);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("<html>Tình trạng hiện tại </html>");
        jLabel26.setPreferredSize(new java.awt.Dimension(63, 26));

        txtBenhSu.setColumns(20);
        txtBenhSu.setRows(5);
        jScrollPane5.setViewportView(txtBenhSu);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("<html>Bệnh sử </html>");
        jLabel27.setPreferredSize(new java.awt.Dimension(63, 26));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMach, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbNhomMau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHuyetAp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNhietDo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNhipTho, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCanNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNhomMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhietDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHuyetAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhipTho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(204, 240, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nội dung khám", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jPanel12.setBackground(new java.awt.Color(204, 240, 255));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("<html>Chẩn đoán sơ bộ</html>");
        jLabel28.setPreferredSize(new java.awt.Dimension(63, 26));

        txtChanDoanSoBo.setColumns(20);
        txtChanDoanSoBo.setRows(5);
        jScrollPane6.setViewportView(txtChanDoanSoBo);

        txtYCThem.setColumns(20);
        txtYCThem.setRows(5);
        jScrollPane7.setViewportView(txtYCThem);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("<html>Yêu cầu thêm</html>");
        jLabel29.setPreferredSize(new java.awt.Dimension(63, 26));

        txtChanDoanSauCung.setColumns(20);
        txtChanDoanSauCung.setRows(5);
        jScrollPane8.setViewportView(txtChanDoanSauCung);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("<html>Chẩn đoán sau cùng</html>");
        jLabel30.setPreferredSize(new java.awt.Dimension(63, 26));

        txtHuongDieuTri.setColumns(20);
        txtHuongDieuTri.setRows(5);
        jScrollPane9.setViewportView(txtHuongDieuTri);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("<html>Hướng điều trị  </html>");
        jLabel31.setPreferredSize(new java.awt.Dimension(63, 26));

        txtChiPhi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtChiPhi.setText("0");
        txtChiPhi.setPreferredSize(new java.awt.Dimension(59, 25));
        txtChiPhi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChiPhiKeyPressed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Chi phí khám : ");
        jLabel32.setPreferredSize(new java.awt.Dimension(63, 26));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane6)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(435, 100));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/giuong_benh_30x30.png"))); // NOI18N
        jButton2.setText("Nhập viện");
        jButton2.setPreferredSize(new java.awt.Dimension(158, 59));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnCapThuoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/thuoc_30x30.png"))); // NOI18N
        btnCapThuoc.setText("Cấp thuốc");
        btnCapThuoc.setPreferredSize(new java.awt.Dimension(158, 59));
        btnCapThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapThuocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(btnCapThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapThuocActionPerformed
        String input;
        if(txtChiPhi.getText() == null || txtChiPhi.getText().equals("")) 
            input = "0"; 
        else 
            input = txtChiPhi.getText(); 
        long chiPhi = Long.parseLong(input);
        if (!txtMaBN.getText().isEmpty() && tableBenhNhan.getSelectedRow() >= 0) {
            if (chiPhi >= 0) {
                BenhAnRequest request = new BenhAnRequest(dsBenhNhan.get(tableBenhNhan.getSelectedRow()).getBenhAnResponse());
                request.setMaBN(txtMaBN.getText());
                request.setCanNang(Float.parseFloat(txtCanNang.getText()));
                request.setNhomMau(cbNhomMau.getSelectedItem().toString());
                request.setNhietDo(Float.parseFloat(txtNhietDo.getText()));
                request.setMach(Integer.parseInt(txtMach.getText()));
                request.setHuyetAp(Integer.parseInt(txtHuyetAp.getText()));
                request.setNhipTho(Integer.parseInt(txtNhipTho.getText()));
                request.setLyDoKham(txtLyDoKham.getText());
                request.setTinhTrangHT(txtTinhTrangHT.getText());
                request.setBenhSu(txtBenhSu.getText());
                request.setChanDoanSoBo(txtChanDoanSoBo.getText());
                request.setYeuCauThem(txtYCThem.getText());
                request.setChanDoanSauCung(txtChanDoanSauCung.getText());
                request.setHuongDieuTri(txtHuongDieuTri.getText());
                request.setChiPhi(chiPhi);
                if (benhAnRepository.updateBenhAn(request) && bnRepository.nhapVien(request.getMaBN())) {
                    CapThuoc.shareInstances.setVisible(true);
                    CapThuoc.shareInstances.init(txtMaBA.getText());
                } else {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi cập nhật bệnh án...");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Chi phí điều trị phải lớn hơn hoặc bằng 0");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn bệnh nhân");
        }
    }//GEN-LAST:event_btnCapThuocActionPerformed

    private void tableBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBenhNhanMouseClicked
        int selectIndex = tableBenhNhan.getSelectedRow();
        txtMaBN.setText(dsBenhNhan.get(selectIndex).getMaBN());
        txtDiaChi.setText(dsBenhNhan.get(selectIndex).getDiaChi());
        txtHoBN.setText(dsBenhNhan.get(selectIndex).getHoBn());
        txtTenBN.setText(dsBenhNhan.get(selectIndex).getTenBn());
        txtNgaySinh.setText(dsBenhNhan.get(selectIndex).getNgaySinh());
        txtGioiTinh.setText(dsBenhNhan.get(selectIndex).getGioiTinh());
        txtSDT.setText(dsBenhNhan.get(selectIndex).getSdt());
        new Thread(() -> {
            lbImage.setIcon(APIManager.loadImageIcon(dsBenhNhan.get(selectIndex).getAvatar(), lbImage.getWidth(), lbImage.getHeight()));
        }).start();
        BenhAnResponse benhAn = dsBenhNhan.get(selectIndex).getBenhAnResponse();
        if (benhAn != null) {
            txtMaBA.setText(benhAn.getMaBA());
            txtYCKham.setText(benhAn.getLyDoKham());
            txtCanNang.setText(benhAn.getCanNang() + "");
            if (benhAn.getNhomMau() == null) {
                cbNhomMau.setSelectedIndex(0);
            } else {
                cbNhomMau.setSelectedItem(benhAn.getNhomMau());
            }
            txtNhietDo.setText(benhAn.getNhietDo() + "");
            txtMach.setText(benhAn.getMach() + "");
            txtHuyetAp.setText(benhAn.getHuyetAp() + "");
            txtNhipTho.setText(benhAn.getNhipTho() + "");
            txtLyDoKham.setText(benhAn.getLyDoKham());
            txtTinhTrangHT.setText(benhAn.getTinhTrangHT());
            txtBenhSu.setText(benhAn.getBenhSu());
            txtChanDoanSoBo.setText(benhAn.getChanDoanSoBo());
            txtYCThem.setText(benhAn.getYeuCauThem());
            txtChanDoanSauCung.setText(benhAn.getChanDoanSauCung());
            txtHuongDieuTri.setText(benhAn.getHuongDieuTri());
        }
    }//GEN-LAST:event_tableBenhNhanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        long chiPhi = Long.parseLong(txtChiPhi.getText());
        if (txtMaBN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn bệnh nhân");
        } else if (chiPhi < 0) {
            JOptionPane.showMessageDialog(this, "Chi phí điều trị phải lớn hơn hoặc bằng 0");
        } else {
            BenhAnRequest request = new BenhAnRequest(dsBenhNhan.get(tableBenhNhan.getSelectedRow()).getBenhAnResponse());
            request.setMaBN(txtMaBN.getText());
            request.setCanNang(Float.parseFloat(txtCanNang.getText()));
            request.setNhomMau(cbNhomMau.getSelectedItem().toString());
            if (!txtNhietDo.getText().equals("")) {
                request.setNhietDo(Float.parseFloat(txtNhietDo.getText()));
            }
            if (!txtMach.getText().equals("")) {
                request.setMach(Integer.parseInt(txtMach.getText()));
            }
            if (!txtHuyetAp.getText().equals("")) {
                request.setHuyetAp(Integer.parseInt(txtHuyetAp.getText()));
            }
            if (!txtNhipTho.getText().equals("")) {
                request.setNhipTho(Integer.parseInt(txtNhipTho.getText()));
            }
            request.setLyDoKham(txtLyDoKham.getText());
            request.setTinhTrangHT(txtTinhTrangHT.getText());
            request.setBenhSu(txtBenhSu.getText());
            request.setChanDoanSoBo(txtChanDoanSoBo.getText());
            request.setYeuCauThem(txtYCThem.getText());
            request.setChanDoanSauCung(txtChanDoanSauCung.getText());
            request.setHuongDieuTri(txtHuongDieuTri.getText());
            request.setChiPhi(chiPhi);
            NhapVien.sharedInstances.setVisible(true);
            NhapVien.sharedInstances.setBenhAnRequest(request);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String maBN = txtMaBN.getText();
        if (!maBN.isEmpty()) {
            if (bnRepository.xuatVien(maBN)) {
                JOptionPane.showMessageDialog(this, "Bệnh nhân đã được xuất viện...");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra, vui lòng thử lại...");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cần chọn bệnh nhân để xóa");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtChiPhiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChiPhiKeyPressed
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            txtChiPhi.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE
                    || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtChiPhi.setEditable(true);
            } else {
                txtChiPhi.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtChiPhiKeyPressed

    private void txtCanNangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCanNangKeyPressed
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            txtCanNang.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE
                    || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtCanNang.setEditable(true);
            } else {
                txtCanNang.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtCanNangKeyPressed

    private void txtMachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMachKeyPressed
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            txtMach.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE
                    || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtMach.setEditable(true);
            } else {
                txtMach.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtMachKeyPressed

    private void txtHuyetApKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHuyetApKeyPressed
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            txtHuyetAp.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE
                    || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtHuyetAp.setEditable(true);
            } else {
                txtHuyetAp.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtHuyetApKeyPressed

    private void txtNhietDoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhietDoKeyPressed
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            txtNhietDo.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE
                    || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtNhietDo.setEditable(true);
            } else {
                txtNhietDo.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtNhietDoKeyPressed

    private void txtNhipThoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhipThoKeyPressed
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            txtNhipTho.setEditable(true);
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE
                    || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                txtNhipTho.setEditable(true);
            } else {
                txtNhipTho.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtNhipThoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapThuoc;
    private javax.swing.JComboBox<String> cbNhomMau;
    private javax.swing.JLabel dsgrd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lbImage;
    private javax.swing.JTable tableBenhNhan;
    private javax.swing.JTextArea txtBenhSu;
    private javax.swing.JTextField txtCanNang;
    private javax.swing.JTextArea txtChanDoanSauCung;
    private javax.swing.JTextArea txtChanDoanSoBo;
    private javax.swing.JTextField txtChiPhi;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGioiTinh;
    private javax.swing.JTextField txtHoBN;
    private javax.swing.JTextArea txtHuongDieuTri;
    private javax.swing.JTextField txtHuyetAp;
    private javax.swing.JTextArea txtLyDoKham;
    private javax.swing.JTextField txtMaBA;
    private javax.swing.JTextField txtMaBN;
    private javax.swing.JTextField txtMach;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNhietDo;
    private javax.swing.JTextField txtNhipTho;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenBN;
    private javax.swing.JTextArea txtTinhTrangHT;
    private javax.swing.JTextArea txtYCKham;
    private javax.swing.JTextArea txtYCThem;
    // End of variables declaration//GEN-END:variables
}
