/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quan.datn.view.panel;

import com.quan.datn.model.PhongKham;
import com.quan.datn.model.response.PhongBenhResponse;
import com.quan.datn.network.PhongBenhRepository;
import com.quan.datn.network.PhongKhamRepository;
import com.quan.datn.view.ThemPhongBenh;
import com.quan.datn.view.ThemPhongKham;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class PNQLPB extends javax.swing.JPanel {

    /**
     * Creates new form PNQLPB
     */
    private final PhongKhamRepository pkRepository;
    private List<PhongKham> listPhongKham;
    private final PhongBenhRepository phongBenhRepository;
    private List<PhongBenhResponse> listPhongBenh;

    public PNQLPB() {
        initComponents();
        pkRepository = new PhongKhamRepository();
        phongBenhRepository = new PhongBenhRepository();
        loadData();
    }

    public void loadData() {
        new Thread(() -> {
            getListPhongKham();
            getListPhongBenh();
        }).start();
    }

    public void getListPhongKham() {
        listPhongKham = pkRepository.getAllPhongKham();
        DefaultTableModel mode = (DefaultTableModel) tbPhongKham.getModel();
        mode.setRowCount(0);
        if (listPhongKham != null && listPhongKham.size() > 0) {
            Object[] row = new Object[4];
            for (int i = 0; i < listPhongKham.size(); i++) {
                row[0] = i;
                row[1] = listPhongKham.get(i).getMaPK();
                row[2] = listPhongKham.get(i).getTenPK();
                if (listPhongKham.get(i).getBacSi() != null) {
                    String fullName = listPhongKham.get(i).getBacSi().getHo() + " " + listPhongKham.get(i).getBacSi().getTen();
                    row[3] = fullName;
                } else {
                    row[3] = "";
                }
                mode.addRow(row);
            }
        } else {
            listPhongKham = new ArrayList<>();
        }
    }

    public void getListPhongBenh() {
        listPhongBenh = phongBenhRepository.getAllPhongBenh();
        DefaultTableModel mode = (DefaultTableModel) tbPhongBenh.getModel();
        mode.setRowCount(0);
        if (listPhongBenh != null && listPhongBenh.size() > 0) {
            Object[] row = new Object[3];
            for (int i = 0; i < listPhongBenh.size(); i++) {
                row[0] = i;
                row[1] = listPhongBenh.get(i).getMaPB();
                row[2] = listPhongBenh.get(i).getTenPB();
                mode.addRow(row);
            }
        } else {
            listPhongBenh = new ArrayList<>();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPhongBenh = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbPhongKham = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(214, 240, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng bệnh", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 643));

        tbPhongBenh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbPhongBenh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phòng bệnh", "Tên phòng bệnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPhongBenh.setGridColor(new java.awt.Color(204, 255, 204));
        tbPhongBenh.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        tbPhongBenh.setMinimumSize(new java.awt.Dimension(600, 156));
        tbPhongBenh.setRowHeight(26);
        tbPhongBenh.setSelectionBackground(new java.awt.Color(183, 219, 255));
        tbPhongBenh.setSelectionForeground(new java.awt.Color(0, 102, 255));
        tbPhongBenh.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tbPhongBenh);
        if (tbPhongBenh.getColumnModel().getColumnCount() > 0) {
            tbPhongBenh.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/save_30x30.png"))); // NOI18N
        jButton5.setText("Thêm");
        jButton5.setToolTipText("");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton5.setPreferredSize(new java.awt.Dimension(128, 39));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/delete_30x30.png"))); // NOI18N
        jButton6.setText("Xóa");
        jButton6.setToolTipText("");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton6.setPreferredSize(new java.awt.Dimension(128, 39));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(214, 240, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng khám", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        tbPhongKham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbPhongKham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phòng khám", "Tên phòng", "Bác sĩ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPhongKham.setGridColor(new java.awt.Color(204, 255, 204));
        tbPhongKham.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        tbPhongKham.setMinimumSize(new java.awt.Dimension(600, 156));
        tbPhongKham.setRowHeight(26);
        tbPhongKham.setSelectionBackground(new java.awt.Color(183, 219, 255));
        tbPhongKham.setSelectionForeground(new java.awt.Color(0, 102, 255));
        tbPhongKham.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tbPhongKham);
        if (tbPhongKham.getColumnModel().getColumnCount() > 0) {
            tbPhongKham.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/save_30x30.png"))); // NOI18N
        jButton3.setText("Thêm");
        jButton3.setToolTipText("");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setPreferredSize(new java.awt.Dimension(128, 39));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/delete_30x30.png"))); // NOI18N
        jButton4.setText("Xóa");
        jButton4.setToolTipText("");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.setPreferredSize(new java.awt.Dimension(128, 39));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (tbPhongKham.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Cần chọn phòng để có thể xóa ...");
        } else {
            int input = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa phòng này?", "Select an Option...",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (input == 0) {
                String maPK = listPhongKham.get(tbPhongKham.getSelectedRow()).getMaPK();
                if (pkRepository.deletePhongKham(maPK)) {
                    JOptionPane.showMessageDialog(this, "Xóa phòng thành công");
                    getListPhongKham();
                } else {
                    JOptionPane.showMessageDialog(this, "Có lỗi xảy ra, Có thể do phòng vẫn đang được sử dụng.\n Vui lòng kiểm tra lại ...");
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (tbPhongBenh.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Cần chọn phòng để có thể xóa ...");
        } else {
            int input = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa phòng này?", "Select an Option...",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (input == 0) {
                String maPB = listPhongBenh.get(tbPhongBenh.getSelectedRow()).getMaPB();
                if (phongBenhRepository.deletePhongBenh(maPB)) {
                    JOptionPane.showMessageDialog(this, "Xóa phòng thành công");
                    getListPhongBenh();
                } else {
                    JOptionPane.showMessageDialog(this, "Có lỗi xảy ra, vui lòng thử lại ...");
                }
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ThemPhongBenh.sharedInstances.setVisible(true);
        ThemPhongBenh.sharedInstances.generatorMaPB();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ThemPhongKham.sharedInstances.setVisible(true);
        ThemPhongKham.sharedInstances.showListBacSi();


    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbPhongBenh;
    private javax.swing.JTable tbPhongKham;
    // End of variables declaration//GEN-END:variables
}
