/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quan.datn.view;

import com.quan.datn.model.response.BenhAnResponse;
import com.quan.datn.network.BenhAnRepository;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class BenhAnView extends javax.swing.JFrame {

    /**
     * Creates new form BenhAnView
     */
    public static BenhAnView sharedInstances = new BenhAnView();
    private final BenhAnRepository benhAnRepository;
    private List<BenhAnResponse> dsBenhAn;
    public String maBN;
    
    public BenhAnView() {
        initComponents();
        benhAnRepository = new BenhAnRepository();
        dsBenhAn = new ArrayList<>();
    }

    public void loadData() {
        dsBenhAn = benhAnRepository.getAllBenhAn( this.maBN);
        showListBenhAn();
    }

    private void showListBenhAn() {
        DefaultTableModel mode = (DefaultTableModel) tableBN.getModel();
        mode.setRowCount(0);
        if (!dsBenhAn.isEmpty()) {
            Object[] row = new Object[19];
            for (int i = 0; i < dsBenhAn.size(); i++) {
                row[0] = i;
                row[1] = dsBenhAn.get(i).getMaBA();
                row[2] = dsBenhAn.get(i).getThoiGianKham();
                row[3] = dsBenhAn.get(i).getLyDoKham();
                row[4] = dsBenhAn.get(i).getTinhTrangHT();
                row[5] = dsBenhAn.get(i).getBenhSu();
                row[6] = dsBenhAn.get(i).getChanDoanSoBo();
                row[7] = dsBenhAn.get(i).getYeuCauThem();
                row[8] = dsBenhAn.get(i).getChanDoanSauCung();
                row[9] = dsBenhAn.get(i).getHuongDieuTri();
                row[10] = dsBenhAn.get(i).getCanNang();
                row[11] = dsBenhAn.get(i).getNhomMau();
                row[12] = dsBenhAn.get(i).getNhietDo();
                row[13] = dsBenhAn.get(i).getMach();
                row[14] = dsBenhAn.get(i).getHuyetAp();
                row[15] = dsBenhAn.get(i).getNhipTho();
                row[16] = dsBenhAn.get(i).getPhongKham().getTenPK();
                if(dsBenhAn.get(i).getPhongBenh() != null){
                    row[17] = dsBenhAn.get(i).getPhongBenh().getTenPB();
                }else{
                    row[17] = "";
                }
                if (dsBenhAn.get(i).getPhongKham().getBacSi() != null) {
                    String hoTenBS = dsBenhAn.get(i).getPhongKham().getBacSi().getHo() + " " +dsBenhAn.get(i).getPhongKham().getBacSi().getTen();
                    row[18] = hoTenBS;
                }else{
                    row[18] = "";
                }
                mode.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBN = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btn_Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Danh sách bệnh án");

        jPanel2.setBackground(new java.awt.Color(214, 240, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Bệnh Án", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 300));

        tableBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableBN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Bệnh Án", "Thời gian khám", "Lý Do Khám", "Tình Trạng Hiện Tại", "Bệnh Sử", "Chẩn Đoán Sơ Bộ", "Yêu Cầu Thêm", "Chẩn Đoán Sau Cùng", "Hướng Điều Trị", "Cân Nặng", "Nhóm Máu", "Nhiệt Độ", "Mạch", "Huyết Áp", "Nhịp Thở", "Phòng Khám", "Phòng Bệnh", "Bác Sĩ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBN.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableBN.setGridColor(new java.awt.Color(204, 255, 204));
        tableBN.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        tableBN.setMinimumSize(new java.awt.Dimension(600, 156));
        tableBN.setRowHeight(26);
        tableBN.setSelectionBackground(new java.awt.Color(183, 219, 255));
        tableBN.setSelectionForeground(new java.awt.Color(0, 102, 255));
        tableBN.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tableBN);
        if (tableBN.getColumnModel().getColumnCount() > 0) {
            tableBN.getColumnModel().getColumn(0).setMinWidth(60);
            tableBN.getColumnModel().getColumn(1).setMinWidth(150);
            tableBN.getColumnModel().getColumn(2).setMinWidth(150);
            tableBN.getColumnModel().getColumn(3).setMinWidth(350);
            tableBN.getColumnModel().getColumn(4).setMinWidth(350);
            tableBN.getColumnModel().getColumn(5).setMinWidth(350);
            tableBN.getColumnModel().getColumn(6).setMinWidth(350);
            tableBN.getColumnModel().getColumn(7).setMinWidth(350);
            tableBN.getColumnModel().getColumn(8).setMinWidth(350);
            tableBN.getColumnModel().getColumn(9).setMinWidth(350);
            tableBN.getColumnModel().getColumn(10).setMinWidth(100);
            tableBN.getColumnModel().getColumn(11).setMinWidth(100);
            tableBN.getColumnModel().getColumn(12).setMinWidth(80);
            tableBN.getColumnModel().getColumn(13).setMinWidth(80);
            tableBN.getColumnModel().getColumn(14).setMinWidth(100);
            tableBN.getColumnModel().getColumn(15).setMinWidth(80);
            tableBN.getColumnModel().getColumn(16).setMinWidth(250);
            tableBN.getColumnModel().getColumn(17).setMinWidth(250);
            tableBN.getColumnModel().getColumn(18).setMinWidth(250);
        }

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/ic_reload_30x30.png"))); // NOI18N
        btnSave.setText("Tải lại");
        btnSave.setPreferredSize(new java.awt.Dimension(158, 59));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btn_Close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/icon_X_30x30.png"))); // NOI18N
        btn_Close.setText("Đóng");
        btn_Close.setPreferredSize(new java.awt.Dimension(158, 59));
        btn_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        loadData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btn_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BenhAnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BenhAnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BenhAnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BenhAnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BenhAnView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btn_Close;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableBN;
    // End of variables declaration//GEN-END:variables
}
