/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.quan.datn.view;

import com.quan.datn.model.request.BenhAnRequest;
import com.quan.datn.model.response.PhongBenhResponse;
import com.quan.datn.network.BenhAnRepository;
import com.quan.datn.network.BenhNhanRepository;
import com.quan.datn.network.PhongBenhRepository;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class NhapVien extends javax.swing.JFrame {

    /**
     * Creates new form NhapVien
     */
    public static NhapVien sharedInstances = new NhapVien();
    private final PhongBenhRepository phongBenhRepository;
    private final BenhAnRepository benhAnRepository;
    private final BenhNhanRepository benhNhanRepository;
    private List<PhongBenhResponse> dsPhongBenh;
    private BenhAnRequest request;
    
    public NhapVien() {
        initComponents();
        phongBenhRepository = new PhongBenhRepository();
        benhAnRepository = new BenhAnRepository();
        benhNhanRepository = new BenhNhanRepository();
        getListPhongBenh();
    }

    public void setBenhAnRequest(BenhAnRequest request){
        this.request = request;
    }
    
    public void getListPhongBenh() {
        new Thread(() -> {
            dsPhongBenh = phongBenhRepository.getAllPhongBenh();
            DefaultTableModel mode = (DefaultTableModel) tablePhongBenh.getModel();
            mode.setRowCount(0);
            if (dsPhongBenh != null && dsPhongBenh.size() > 0) {
                Object[] row = new Object[3];
                for (int i = 0; i < dsPhongBenh.size(); i++) {
                    row[0] = i;
                    row[1] = dsPhongBenh.get(i).getMaPB();
                    row[2] = dsPhongBenh.get(i).getTenPB();
                    mode.addRow(row);
                }
            } else {
                dsPhongBenh = new ArrayList<>();
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePhongBenh = new javax.swing.JTable();
        btrnClose = new javax.swing.JButton();
        btnNhapVien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lựa chọn phòng bệnh cho bệnh nhân");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lựa chọn phòng bệnh", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tablePhongBenh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablePhongBenh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Mã Phòng Bệnh", "Tên Phòng Bệnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePhongBenh.setGridColor(new java.awt.Color(204, 255, 204));
        tablePhongBenh.setMaximumSize(new java.awt.Dimension(2147483647, 200));
        tablePhongBenh.setMinimumSize(new java.awt.Dimension(600, 156));
        tablePhongBenh.setRowHeight(26);
        tablePhongBenh.setSelectionBackground(new java.awt.Color(183, 219, 255));
        tablePhongBenh.setSelectionForeground(new java.awt.Color(0, 102, 255));
        tablePhongBenh.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablePhongBenh);
        if (tablePhongBenh.getColumnModel().getColumnCount() > 0) {
            tablePhongBenh.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btrnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btrnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/icon_X_25x25.png"))); // NOI18N
        btrnClose.setText("Đóng");
        btrnClose.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btrnClose.setPreferredSize(new java.awt.Dimension(128, 39));
        btrnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrnCloseActionPerformed(evt);
            }
        });

        btnNhapVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhapVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/quan/datn/images/giuong_benh_30x30.png"))); // NOI18N
        btnNhapVien.setText("Nhập");
        btnNhapVien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhapVien.setPreferredSize(new java.awt.Dimension(128, 39));
        btnNhapVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(btnNhapVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btrnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btrnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btrnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btrnCloseActionPerformed

    private void btnNhapVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapVienActionPerformed
        int selectIndex = tablePhongBenh.getSelectedRow();
        if (selectIndex >= 0) {
            String maPB = dsPhongBenh.get(selectIndex).getMaPB();
            request.setMaPB(maPB);
            if (benhAnRepository.updateBenhAn(request)) {
                if (benhNhanRepository.nhapVien(request.getMaBN())) {
                    JOptionPane.showMessageDialog(this, "Bệnh nhân đã được nhập viện điều trị...");
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi...");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi cập nhật bệnh án...");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Cần chọn phòng cho bệnh nhân");
        }
    }//GEN-LAST:event_btnNhapVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapVien;
    private javax.swing.JButton btrnClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePhongBenh;
    // End of variables declaration//GEN-END:variables
}
